# Generated by Django 2.2.16 on 2023-02-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230202_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Напишите свой пост', verbose_name='Текст поста'),
        ),
    ]
